---
all:
  vars:
    ansible_user: cisco
    ansible_ssh_pass: cisco
    ping_target:
    - 172.16.1.1
    - 172.16.1.100
    - 172.16.1.101
    - 172.16.1.105
    local_users:
      u1: p1
      u2: p2
      u3: p3

  children:
    ios:
      hosts:
        r1.lab.local:
          ansible_host: 172.16.1.100
        r2.lab.local:
          ansible_host: 172.16.1.102
      vars:
        ansible_network_os: ios

    nxos:
      hosts:
        s1.lab.local:
          ansible_host: 172.16.1.101
      vars:
        ansible_network_os: nxos

    junos:
      hosts:
        srx.lab.local:
          ansible_host: 172.16.1.13
      vars:
        ansible_user: admin
        ansible_ssh_pass: admin1
        ansible_network_os: junos
