---
- hosts: ios
  vars:
    ansible_command_timeout: 30
  tasks:
  - name: "Ping targets from IOS devices"
    ios_command:
      commands: ping vrf Mgmt-intf {{item}}
    loop: "{{ping_target}}"
    register: result
    failed_when: "not '!!!' in result.stdout[0]"
    ignore_errors: yes

- hosts: nxos
  tasks:
  - name: "Ping targets from NXOS devices"
    nxos_command:
      commands: ping {{item}} vrf management
    with_items: "{{ping_target}}"
    register: result
    failed_when: "not 'icmp_seq' in result.stdout[0]"
    ignore_errors: yes

- hosts: junos
  vars:
    ansible_command_timeout: 30
  tasks:
  - name: "Ping targets from Junos devices"
    junos_command:
      commands: ping {{item}}
      display: xml
    with_items: "{{ping_target}}"
    register: result
    failed_when: "result.output['rpc-reply']['ping-results']['ping-failure'] is defined"
    ignore_errors: yes
