---
- import_playbook: cisco-ios-bgp-as.yml

- hosts: ios
  vars:
  - asnum: 65000
  tasks:
  - assert:
      that: |
        bgp_as is not defined or 
        bgp_as == asnum
      msg:  Wrong BGP AS number {{ bgp_as|default('') }} configured on the box

  - name: "Configure BGP neighbor on Cisco IOS"
    ios_config:
      parents:
        - "router bgp {{ asnum }}"
      lines:
        - "neighbor 172.16.1.101 remote-as 65001"
